name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
          echo "$GITHUB_CONTEXT"
          set
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - run: git diff --name-status ..${{ github.sha }}
    - run: git diff-tree --no-commit-id --name-status -r ..origin/master
    - uses: ./
      with: 
        files: .*
